[package]
name = "roast-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Rust implementations of Robust Asynchronous Schnorr Threshold Signatures (ROAST)"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["cryptography", "crypto", "schnorr", "threshold", "signature"]
categories.workspace = true

[dependencies]
aes.workspace = true
ctr.workspace = true
digest.workspace = true
document-features.workspace = true
frost-core.workspace = true
hkdf.workspace = true
rand = { workspace = true, optional = true }
rand_core.workspace = true
thiserror.workspace = true
parity-scale-codec = { workspace = true, optional = true }
scale-info = { workspace = true, optional = true }

[features]
default = ["serialization"]
#! ## Features
## Enable `serde` support for types that need to be communicated. You
## can use `serde` to serialize structs with any encoder that supports
## `serde` (e.g. JSON with `serde_json`).
serde = ["frost-core/serde"]
## Enable `parity-scale-codec` and `scale-info` support for types
## that need to be communicated.
codec = ["frost-core/codec", "dep:parity-scale-codec", "dep:scale-info"]
## Enable a default serialization format. Enables `serde` and `codec`.
serialization = ["serde", "codec", "frost-core/serialization"]
## Exposes ciphersuite-generic tests for other crates to use.
test-impl = ["dep:rand"]
