[package]
name = "roastbeef"
version = "0.1.0"
authors = ["StackOverflowExcept1on"]
edition = "2021"
description = "A Schnorr signature scheme over the secp256k1 curve that supports ROAST"
repository = "https://github.com/StackOverflowExcept1on/roastbeef"
license = "MIT"
keywords = ["cryptography", "crypto", "threshold", "signature"]
categories = ["cryptography"]

[dependencies]
frost-core = { git = "https://github.com/ZcashFoundation/frost", branch = "expose-verify-signature-share" }
frost-secp256k1 = { git = "https://github.com/ZcashFoundation/frost", branch = "expose-verify-signature-share" }
thiserror = "1.0"

[dev-dependencies]
rand_core = { version = "0.6", features = ["getrandom"] }
