[workspace]
resolver = "2"
members = [
    "roast-core",
]

[workspace.package]
version = "0.1.0"
authors = ["StackOverflowExcept1on"]
edition = "2021"
repository = "https://github.com/StackOverflowExcept1on/roastbeef"
license = "MIT"
categories = ["cryptography"]
