[package]
name = "roastbeef"
version = "0.1.0"
authors = ["StackOverflowExcept1on"]
edition = "2021"
description = "A Schnorr signature scheme over the secp256k1 curve that supports ROAST"
repository = "https://github.com/StackOverflowExcept1on/roastbeef"
license = "MIT"
keywords = ["cryptography", "crypto", "threshold", "signature"]
categories = ["cryptography"]

[dependencies]
frost-core = { git = "https://github.com/ZcashFoundation/frost", branch = "expose-verify-signature-share", features = ["internals"], default-features = false }
rand_core = { version = "0.6", default-features = false }
thiserror-nostd-notrait = { version = "1.0", default-features = false }
thiserror = { version = "1.0", default-features = false, optional = true }

[features]
std = ["dep:thiserror"]
