[package]
name = "roast-secp256k1-tr"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Schnorr signature scheme over the secp256k1 curve that supports ROAST and Taproot."
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["cryptography", "crypto", "secp256k1", "threshold", "signature"]
categories.workspace = true

[dependencies]
document-features.workspace = true
frost-secp256k1-tr.workspace = true
roast-core.workspace = true
sha2.workspace = true

[dev-dependencies]
roast-core = { workspace = true, features = ["test-impl"] }
rand_core = { workspace = true, features = ["getrandom"] }

[features]
default = ["serialization"]
#! ## Features
## Enable `serde` support for types that need to be communicated. You
## can use `serde` to serialize structs with any encoder that supports
## `serde` (e.g. JSON with `serde_json`).
serde = ["roast-core/serde"]
## Enable `parity-scale-codec` and `scale-info` support for types
## that need to be communicated.
codec = ["roast-core/codec"]
## Enable a default serialization format. Enables `serde` and `codec`.
serialization = ["serde", "codec", "roast-core/serialization"]
