name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cargo build
        run: cargo build --release

      - name: Cargo test
        run: cargo test --release

      - name: Cargo clippy
        run: cargo clippy --release --all-targets -- -D warnings

      - name: Cargo fmt
        run: cargo fmt -- --check
